kind: source
spec:
  name: xkcd
  path: hermanschaaf/xkcd
  version: v1.0.0
  destinations: ["sqlite"]
  spec:
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: v1.2.3
  spec:
    connection_string: ./db.sqlite