kind: source
spec:
  name: xkcd
  registry: local
  path: /Users/hermanschaaf/code/writing-cq-plugins/cq-source-xkcd/cq-source-xkcd
  version: v0.0.1
  destinations: ["sqlite"]
  spec:
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: v1.2.3
  spec:
    connection_string: ./db.sql